#version: '3.8'
#services:
#  gateway:
#    build: gateway/
#    image: gateway_image
#    container_name: gateway_container
#    ports:
#      - "8080:8080"
#    depends_on:
#      - server
#      - db
#    environment:
#      - SHAREIT_SERVER_URL=http://server:9090
#
#  server:
#    build: server/
#    image: server_image
#    container_name: server_container
#    ports:
#      - "9090:9090"
#    depends_on:
#    - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
#       - DB_NAME= shareit
#       - POSTGRES_USER=root
#       - POSTGRES_PASSWORD=root
#       - DB_HOST=db
#       - DB_PORT=5432
#
#  db:
#    image: postgres:13.7-alpine
#    container_name: db_container
#    volumes:
#      - /var/lib/postgresql/data/
#    ports:
#      - "6541:5432"
#    environment:
#      - POSTGRES_DB=shareit
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root

version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db

    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root

  db:
    image: postgres:13.7-alpine
    container_name: db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root